### ISSUE TITLE
"getStatus()", "status()", "isStatus()", "hasStatus()", "__get()" exist

### ISSUE THREAD

**Issue by magestein** [yokai-php/sonata-workflow#10]
Hi, Im trying the step by step from https://sonata-project.org/bundles/admin/master/doc/cookbook/recipe_workflow_integration.html

**I get the following error**
`Neither the property "status" nor one of the methods "getStatus()", "status()", "isStatus()", "hasStatus()", "__get()" exist and have public access in class "App\Entity\BlogPost".`

Symfony version: 4.3.3 

A little help please?

**Comment by yann-eugone** [comment]
Hi. Do your `BlogPost` entity has an accessible `status` property?

**Comment by magestein** [comment]
omg  Im so sorry, I was using state in argument and not status.. 👍
