### ISSUE TITLE
Prevent some transition in the admin

### ISSUE THREAD

**Issue by mpoiriert** [yokai-php/sonata-workflow#13]
I have some transition that are executed via a cron. User should not be able to apply those transition from the admin.

Is there a way to do that or I should create a complete other workflow to handle that ?

**Comment by yann-eugone** [comment]
Hello.

There is no such feature in this library.
But in my opinion, this should not be handled here.

If the point is to forbid any authenticated user to perform some
transitions, you should write a transition guard for that purpose.

What do you think?

**Comment by mpoiriert** [comment]
Sorry I just starting using more complex workflow and I forgot about that part. I'll manage something, since it's not really related to a specific user but rather not being use via a specific cron... Probably just doing something like checking that I am on CLI or there is no currently connected user will do the job.
Thanks and sorry to have bother you. Great plugin BTW
