### ISSUE TITLE
Allow transitions without 'edit' role

### ISSUE THREAD

**Issue by DiisMami** [yokai-php/sonata-workflow#14]
I am working on a project where one of our partners needs to look at the Entities and confirm they are correct by forwarding them throught the workflow. I dont want to give them writing access as this would confuse them too much. 

The EDIT role is statically programmed into the code. Is there any way of changing that and connecting it to the guard attributs as set in the `workflow.yaml` ?

**Comment by yann-eugone** [comment]
Hello,

No, as you said, it is hardcoded in the controller. The only thing you can
do, by now, is rewriting the entire action.

Maybe the library should introduce a new permission called `transition`, to
be called on both extension and controller, but we need to test that a lot
before releasing it. As I'm not sure what Sonata will check if we do.

**Comment by yann-eugone** [comment]
Fixed as of [v0.3.0](https://github.com/yokai-php/sonata-workflow/releases/tag/v0.3.0)
