### ISSUE TITLE
Issue with template

### ISSUE THREAD

**Issue by gansky-alexander** [yokai-php/sonata-workflow#21]
I am configured all according to documentation but i got exception about template:

`An exception has been thrown during the rendering of a template ("Place "" is not valid for workflow "order".").`

How can i fix this issue?

**Comment by gansky-alexander** [comment]
Sorry :) 

I figured out what is the issue. My entity contain empty "status". Maybe it will be better to rename the error message to "Your place is "" use "new", ..., ... instead?"

Issue can be closed.

**Comment by yann-eugone** [comment]
Hello @gansky-alexander 

The exception you encoutered was generated by Symfony (https://github.com/symfony/workflow/blob/4.4/Workflow.php#L86).

I believe that this is because an entity under workflow should be initialized with a valid state.
