### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by danaki** [yokai-php/sonata-workflow#33]
```
- yokai/sonata-workflow dev-sonata-4.x-compatibility requires symfony/workflow ^4.4|^5.0 -> found symfony/workflow[v4.4.0, ..., v4.4.42, v5.0.0, ..., v5.4.9] but it conflicts with your root composer.json require (6.0.*).
```

**Comment by yann-eugone** [comment]
Released in [`v0.7.0`](https://github.com/yokai-php/sonata-workflow/releases/tag/v0.7.0)

**Comment by yann-eugone** [comment]
I'm not sure what is the issue here. Maybe Symfony just removed the alias for `Psr\Container\ContainerInterface` in the most recent versions.
But I'm not sure this library has something to do with this error.

**Comment by danaki** [comment]
I dont know what I did but the issue is gone

**Comment by yann-eugone** [comment]
That's my favourite kind of issues :)
