### ISSUE TITLE
Dropdown appears on "show" screen toolbar

### ISSUE THREAD

**Issue by danaki** [yokai-php/sonata-workflow#4]
Even if "show" screen is not configured, transition dropdown is there, just replace "edit" with "show" in the URL to see. Not sure if that a major bug, but "show" screens are usually do not offer to change entity, anyway a configuration option to disable this behavior would be nice to see. Thanks.

**Comment by yann-eugone** [comment]
This is because side menu is generated for both `"show"` and `"edit"` actions.

Maybe we can introduce an option for the WorkflowExtension, that tell for which action the menu should be added (default to `"edit"` only).

**Comment by yann-eugone** [comment]
I changed my mind, default value is `["show", "edit"]` but you can change it anyway.

**Comment by yann-eugone** [comment]
Release in https://github.com/yokai-php/sonata-workflow/releases/tag/v0.1.2
